# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoCantina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('responsavel_preenchimento', models.CharField(max_length=100)),
                ('responsavel_informacao', models.CharField(max_length=100)),
                ('escola', models.CharField(max_length=100)),
                ('nome_cantineiro', models.CharField(max_length=100)),
                ('resposta_alimentos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoCantina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=50)),
                ('resposta_avaliacao', models.CharField(max_length=3)),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.AcompanhamentoCantina')),
            ],
        ),
    ]
